name: "Build & Test"

on:
  push:
    branches:
      - master
    paths:
      - '**'
      # Don't run this workflow if the only files that changed are the
      # following. Make sure this is the same as the "pull_request.paths" list.
      - '!AUTHORS'
      - '!PROBLEM-REPORT-FORM'
      - '!LICENSE'
      - '!Dockerfile**'
      - '!.dockerignore'
      - '!.mailmap'
      - '!deploy/**'
      - '!docs/**'
      - '!**.md'
      - '!**.rst'
      - '!**/.gitignore'
      - '!**/README*'
  pull_request:
    branches:
      - master
    paths:
      - '**'
      # Don't run this workflow if the only files that changed are the
      # following. Make sure this is the same as the "push.paths" list.
      - '!AUTHORS'
      - '!PROBLEM-REPORT-FORM'
      - '!LICENSE'
      - '!Dockerfile**'
      - '!.dockerignore'
      - '!.mailmap'
      - '!deploy/**'
      - '!docs/**'
      - '!**.md'
      - '!**.rst'
      - '!**/.gitignore'
      - '!**/README*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TRIGGERING_COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
  VCPKG_INSTALLED_DIR: ${{ github.workspace }}\vcpkg\installed

jobs:

  build_pi:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout opendds-smart-lock
      uses: actions/checkout@v3
      with:
        path: opendds-smart-lock
    - name: build pi toolchain
      run: |
        cd opendds-smart-lock
        ./smart-lock pi build-toolchain

  build_android_arm64:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout opendds-smart-lock
      uses: actions/checkout@v3
      with:
        path: opendds-smart-lock
    - name: build pi toolchain
      run: |
        cd opendds-smart-lock
        ./smart-lock android build-toolchain-arm64

  build_android_arm:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout opendds-smart-lock
      uses: actions/checkout@v3
      with:
        path: opendds-smart-lock
    - name: build pi toolchain
      run: |
        cd opendds-smart-lock
        ./smart-lock android build-toolchain-arm

  build_android_x86:

    runs-on: ubuntu-22.04

    steps:
    - name: checkout opendds-smart-lock
      uses: actions/checkout@v3
      with:
        path: opendds-smart-lock
    - name: build pi toolchain
      run: |
        cd opendds-smart-lock
        ./smart-lock android build-toolchain-x86
